name: Build and Push PiterLabs to GHCR

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'piterlabs-master-v2.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/pedroprobolsas/piterlabs-front:latest

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/pedroprobolsas/piterlabs-api:latest

      - name: Deploy to VPS
        continue-on-error: true
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker service update --image ghcr.io/pedroprobolsas/piterlabs-front:latest piterlabs_front --with-registry-auth --force
            docker service update --image ghcr.io/pedroprobolsas/piterlabs-api:latest piterlabs_api --with-registry-auth --force
